name = "sairaala-haku-cache-proxy"
type = "javascript"
workers_dev = true
vars = { ENVIRONMENT = "dev" }

[env.production]
vars = { ENVIRONMENT = "production" }
workers_dev = false
route = "synnytyssairaalat.korvenlaita.fi/*"
