name: Pr Checks 

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  check-app:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout
        uses: actions/checkout@v2
      - name: Set up Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.8.2
      - name: Lint public
        run: deno fmt --check ./public/
  check-cf-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install
        run: cd cache-proxy/ && npm ci
      - name: Lint cf worker
        run: cd cache-proxy/ && npm run lint 
  check-front-end:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout
        uses: actions/checkout@v2
      - name: Set up Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.8.2
      - name: Lint public
        run: deno fmt --check ./public/
  trigger-deploy:
    runs-on: ubuntu-latest
    needs:
      - check-app
      - check-cf-worker
      - check-front-end
    if: github.ref == 'refs/heads/main'
    steps:
      - run: echo FOO


