name: Deploy

on:
  repository_dispatch:
    types:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # to deploy exact ref that triggerd
      # could also read the github.event.client_payload.sha to e.g. tag deployments
      # with:
      #   ref: ${{ github.event.client_payload.ref }}
      - name: Deploy web server
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "synnytyssairaala-haku" 
          heroku_email: "n.p.ahonen@gmail.com"
          usedocker: true
      - name: Deploy proxy
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
          workingDirectory: 'cache-proxy'
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
